// lecture 11/React/comparison-tutorial-react/src/components/Faq/Faq.js
import React, { Component } from 'react';
import "./Faq.css"
import axios from 'axios';


class Faq extends Component {

    constructor(props)
    {
       super(props);
       this.state = {
           faqs: []
       };
    }

    componentDidMount() {
        axios.get('https://jsonplaceholder.typicode.com/posts')
        .then(res => {
          const faqs = res.data.slice(0, 10);
          this.setState ({faqs});
        })
    }

    render() {
        return (
            <div>
                <div className="container">
                    <div className="section">
                    <h1 className="title">FAQ </h1>
                    <h2 className="subtitle is-4">Lorum ipsum, lorem ipsum, etc </h2>

                        <div className="columns">
                        { 
                            this.state.faqs.map(faq =>
                            <div className="column is-one-third">
                                <div className="card">
                                    <div className="card-content">
                                    <p className="title"> {faq.title}  </p>
                                    <p className="answer"> {faq.body}  </p>
                                </div>
                                </div>
                            </div>
                         )}
                        </div>
                    </div>
                </div>
            </div>
        );
    }
}

export default Faq;

// lecture 11/Vue/comparison-tutorial-vue/src/components/Faq.vue
<!-- Define a component and bind them to an HTML element -->
<template>
  <div id="faq">
    <div class="container">
      <div class="section">
        <h1 class="title">FAQ </h1>
        <h2 class="subtitle is-4">Lorum ipsum, lorem ipsum, etc </h2>

          <div class="columns" v-if="faqs && faqs.length">
            <div class="column is-one-third" v-for="faq of faqs">
                <div class="card">
                  <div class="card-content">
                    <p class="title"> {{faq.title}}  </p>
                    <p class="answer"> {{faq.body}}  </p>
                </div>
              </div>
            </div>
            <div class="column">
              Second column
            </div>
            <div class="column">
              Third column
            </div>
            <div class="column">
              Fourth column
            </div>
          </div>

      </div>
    </div>



  </div>
</template>

<script>
import axios from 'axios'

export default {
  name: 'faq',
  data: () => ({
    faqs: [],
    errors: []
  }), 
  created() {
    axios.get('https://jsonplaceholder.typicode.com/posts')
     .then(response => {
       this.faqs = response.data.slice(10)
     })
     .catch(e => {
       this.errors.push(e)
     })
  }
}
</script>


<!-- Add "scoped" attribute to limit CSS to this component only -->
<style lang="sass" scoped>
@import '../mq'

.pd 
  padding: 2.5em 0 1.5em 0

.answer
  margin-top: 10px !important
  color: gray

.columns
  flex-wrap: wrap

</style>
